import type { Metadata } from "next";
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/700.css";
import "@fontsource/great-vibes/400.css";
import "./globals.css";
import StyledComponentsRegistry from "./StyledComponentsRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body style={{ fontFamily: 'Poppins, Arial, sans-serif' }}>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
